#!/bin/bash

JAR="../target/webtablestitching-1.0-jar-with-dependencies.jar"
CLS="de.uni_mannheim.informatik.dws.tnt.match.cli.CreateUnionTables"

TABLES="../examples/tables/"
RESULTS="../examples/union/"

java -cp $JAR $CLS -web $TABLES -results $RESULTS
